# Generated by Django 5.0.6 on 2024-06-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearlycards',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
